use student;
show tables;
create table student(rollno int, name varchar(30),class varchar(5),age int);
insert into student values(43,'Parth','SY-A',19);
insert into student values(50,'Virendra','SY-A',21);
insert into student values(33,'Ishwar','SY-A',20);
insert into student values(44,'Ganesh','SY-A',20);
insert into student values(47,'Yash','SY-A',19);
create table course(cid int,rollno int);
insert into course values(11,33);
insert into course values(2,23);
insert into course values(4,67);
insert into course values(5,43);
insert into course values(6,50);
select student.name, student.rollno, course.cid from student inner join course on course.rollno=student.rollno;
select student.name, student.rollno, course.cid from student left join course on course.rollno=student.rollno;
select student.name, student.rollno, course.cid from student right join course on course.rollno=student.rollno;
select student.name, student.rollno, course.cid from student full join course on course.rollno=student.rollno;
select student.name, student.rollno, course.cid from student left join course on course.rollno=student.rollno union select student.name, student.rollno, course.cid from student right join course on course.rollno=student.rollno;
